# Generated by Django 6.0.5 on 2026-06-16 03:53

import django.db.models.deletion
import djultra.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', djultra.fields.CharField(blank=True, choices=[('new', 'New'), ('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='new', max_length=10, null=True)),
                ('first_name', djultra.fields.CharField(blank=True, default='', max_length=255, null=True)),
                ('last_name', djultra.fields.CharField(blank=True, default='', max_length=255, null=True)),
                ('full_name', djultra.fields.CharField(blank=True, default='', editable=False, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('birthday', djultra.fields.DateField(blank=True, max_length=255, null=True)),
                ('birthplace', djultra.fields.CharField(blank=True, default='', max_length=255, null=True)),
                ('invitation_token', models.UUIDField(editable=False, null=True, unique=True)),
                ('invitation_token_created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('signin_token', models.UUIDField(editable=False, null=True, unique=True)),
                ('signin_token_created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('terms_accepted_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'serializer_defaults': {'fields': ['id', 'first_name', 'last_name', 'full_name', 'email', 'birthday', 'birthplace', 'status']},
            },
        ),
        migrations.CreateModel(
            name='PersonLoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_user', to='djultra.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
