# Generated by Django 6.0.5 on 2026-06-23 18:59

import djultra.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djultra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', djultra.fields.AdvancedCharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', djultra.fields.AdvancedCharField(blank=True, default='', max_length=255)),
                ('status', djultra.fields.AdvancedCharField(blank=True, choices=[('new', 'New'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='new', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
