# Generated by Django 6.0.5 on 2026-06-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djultra', '0002_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.RemoveField(
            model_name='personloginuser',
            name='person',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonLoginUser',
        ),
    ]
